### ISSUE TITLE
Graphite graphs Tab missing in services 

### ISSUE THREAD

**Issue by tarak666** [shinken-monitoring/mod-graphite#11]
Hi,

I have Graphite installed in centos and working fine in shinken2.2, after i upgrade webui to BS3-1.0 Graphs tab is missing from detals page.

![1](https://cloud.githubusercontent.com/assets/3509727/7606011/afb723f0-f972-11e4-921d-b85539f8ca9c.PNG)

Thanks,
Tarak

**Comment by mohierf** [comment]
Please check that you installed the ui-graphite module in Shinken

**Comment by tarak666** [comment]
Yes, I have  ui-graphite module and it is working in old version webui. In dashboard also its working
![4](https://cloud.githubusercontent.com/assets/3509727/7625802/2e289ca8-fa1a-11e4-981e-a8394407a3e4.PNG)

**Comment by mohierf** [comment]
If you have some graphs in the dashboard view, you should have in the element view ... please check your `webui/plugins/eltdetail/plugin.cfg` file. This file allows to define which tabs are present ...

**Comment by tarak666** [comment]
I have "tab_graphs=yes " in webui/plugins/eltdetail/plugin.cfg file. But when Inspect Element, I seestyle="display: none"

class="link_to_tab" href="#downtimes" data-toggle="tab">Downtimes
 class="active">class="link_to_tab" href="#graphs" data-toggle="tab" id="tab_to_graphs" style="display: none;">Graphs

**Comment by mohierf** [comment]
I checked in the eltview plugin and this element is built in the HTML when `tab_graphs=yes` but hidden when the ui_graphite module does not find any graphs to display ... in fact, the module does not build correctly the URI for the graphs.

 Please check if you have some exception logs in the brokerd.log ... ?

 On my test server, I use a modified version of ui-graphite and I do not have any problem, except when my graphite is down :/P

**Comment by tarak666** [comment]
Hi, 
Sorry for Late reply, i have some error in elt plugin and Could you please tell me how to modified version of ui-graphite.

[root@localhost eltdetail]# python eltdetail.py
Traceback (most recent call last):
  File "eltdetail.py", line 126, in <module>
    load_cfg()
  File "eltdetail.py", line 54, in load_cfg
    from webui.config_parser import config_parser
ImportError: No module named webui.config_parser

And in My brokerd.log

[1432066031] INFO: [broker-master] [LogStoreMongoDB] This line is invalid: [1432066030] INFO: [Shinken] Stalking Memory: Ok : memory consumption is 32%

[1432066047] INFO: [broker-master] [LogStoreMongoDB] This line is invalid: [1432066046] INFO: [Shinken] Stalking Reboot: Ok: uptime is 427days (36970559s)

[1432066083] INFO: [broker-master] [LogStoreMongoDB] This line is invalid: [1432066082] INFO: [Shinken] Stalking Reboot: Ok: uptime is 326days (28194559s)

[1432066085] INFO: [broker-master] [LogStoreMongoDB] This line is invalid: [1432066085] INFO: [Shinken] Stalking Load Average: Ok: load average is good 0.00,0.02,0.03

[1432066104] INFO: [broker-master] [LogStoreMongoDB] This line is invalid: [1432066103] INFO: [Shinken] Stalking Reboot: Ok: uptime is 64days (5531090s)

[1432066771] WARNING: [broker-master] [webui] The mod ui-graphite raise an exception: '', I'm tagging it to restart later
[1432066771] INFO: [broker-master] Trying to init module: ui-graphite

Thanks,
Tarak

**Comment by mohierf** [comment]
Please check if you have a _config_parser.py_ in your webui directory (where module.py is located). If not, you do not have the full BS3 webui installed ...

**Comment by mohierf** [comment]
@tarak666 : Does the problem still exists ?

**Comment by tarak666** [comment]
Yes, Still we have problem, I did installed full BS3 webui, But no luck.
Graphs are not showing and even now i do not see any error message in broker.log file for ui-graphite.

**Comment by mohierf** [comment]
This problem do not occur with the most recent webui2, graphite2 and ui-graphite2 ... as of it, I close this issue.
